In [1]:
import pandas as pd
import numpy as np
import random as rnd

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.optimizers import Adam

from sklearn.metrics import mean_squared_error,mean_absolute_error,explained_variance_score

In [2]:
df = pd.read_csv('processed_3_kayseri_houses_data.csv')
df = df.drop(['Şehir'], axis=1)
df = df.drop(['Türü'], axis=1)

df.head()

Binanın Yaşı  Binanın Kat Sayısı  Kullanım Durumu  Net Metrekare  \
0             0                   7                0            150   
1             0                   2                0            125   
2             8                   9                0            100   
3             8                  11                2            155   
4             4                  13                0            135   

   Oda Sayısı  Bulunduğu Kat  Isıtma Tipi  House Price  İlçe  Mahalle  
0           9              1            5      3200000     4       47  
1           7              8            5      4500000     3       36  
2           4              8            6       920000     4       17  
3           8              2            6      2600000     4      135  
4           7              2            7      2300000     4      127

In [49]:
X = df.drop(['House Price'], axis=1)
y = df['House Price']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [5]:
X_train.shape

(1064, 9)

In [50]:
scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train.max()

1.0000000000000002

In [51]:
X_train.min()

0.0

In [52]:
model = Sequential()

# input layer
model.add(Dense(19,activation='relu'))

# hidden layers
model.add(Dense(19,activation='relu'))
model.add(Dense(19,activation='relu'))
model.add(Dense(19,activation='relu'))

# output layer
model.add(Dense(1))

model.compile(optimizer='adam',loss='mse')

In [53]:
model.fit(x=X_train,y=y_train.values,
          validation_data=(X_test,y_test.values),
          batch_size=128,epochs=400)

Epoch 1/400
10/10 [==============================] - 1s 16ms/step - loss: 106848267010048.0000 - val_loss: 17046871998464.0000
Epoch 2/400
10/10 [==============================] - 0s 4ms/step - loss: 106848250232832.0000 - val_loss: 17046871998464.0000
Epoch 3/400
10/10 [==============================] - 0s 5ms/step - loss: 106848258621440.0000 - val_loss: 17046869901312.0000
Epoch 4/400
10/10 [==============================] - 0s 4ms/step - loss: 106848250232832.0000 - val_loss: 17046866755584.0000
Epoch 5/400
10/10 [==============================] - 0s 4ms/step - loss: 106848250232832.0000 - val_loss: 17046864658432.0000
Epoch 6/400
10/10 [==============================] - 0s 4ms/step - loss: 106848250232832.0000 - val_loss: 17046859415552.0000
Epoch 7/400
10/10 [==============================] - 0s 4ms/step - loss: 106848250232832.0000 - val_loss: 17046852075520.0000
Epoch 8/400
10/10 [==============================] - 0s 4ms/step - loss: 106848250232832.0000 - val_loss: 17046836346

In [54]:
new_data = pd.DataFrame({'Binanın Yaşı': [2],
                         'Binanın Kat Sayısı': [10],
                         'Kullanım Durumu': [2],
                         'Net Metrekare': [100],
                         'Oda Sayısı': [7],
                         'Bulunduğu Kat': [1],
                         'Isıtma Tipi': [7],
                         'İlçe': [4],
                         'Mahalle': [11],
                        })
new_data

Binanın Yaşı  Binanın Kat Sayısı  Kullanım Durumu  Net Metrekare  \
0             2                  10                2            100   

   Oda Sayısı  Bulunduğu Kat  Isıtma Tipi  İlçe  Mahalle  
0           7              1            7     4       11

In [55]:
y_pred = model.predict(new_data)  # predicted values
y_pred

1/1 [==============================] - 0s 63ms/step


array([[2.4914582e+08]], dtype=float32)

In [56]:
house = df.drop('House Price',axis=1).iloc[0]
house = scaler.transform(house.values.reshape(-1, 9))
house

C:\Users\YSK\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([[0.        , 0.08      , 0.        , 0.03023432, 0.31034483,
        0.09090909, 0.45454545, 0.4       , 0.34057971]])

In [48]:
prediction = model.predict(house)[0,0]
prediction

1/1 [==============================] - 0s 19ms/step


3361662.2

In [57]:
original = df.iloc[0]['House Price']
original

3200000

In [60]:
model.predict(X_test)[10:20]

10/10 [==============================] - 0s 1ms/step


array([[3392817. ],
       [2975256.2],
       [2478670.8],
       [2473401.2],
       [2084761.9],
       [5161325. ],
       [2962892.2],
       [2349161. ],
       [3353241. ],
       [2416549.8]], dtype=float32)

In [61]:
y_test[10:20]

686      2750000
192      1530000
824      1695000
641      1720000
1301     1250000
438     16900000
1091     2585000
1299     2250000
34       2850000
54       1499000
Name: House Price, dtype: int64